### ISSUE TITLE
Standardize docstrings

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/IntervalLinearAlgebra.jl#36]
At the moment each docstring has it's own style  

 - [x] Follow [this format](https://juliareach.github.io/JuliaReachDevDocs/latest/guidelines/#Writing-docstrings-1)
   - [x] utils docstrings #43 
   - [x] classify docstrings #43 
   - [x] hull docstrings #48 
   - [x] oettli docstrings #41 
   - [x] precondition docstrings #48 
   - [x] solve docstrings #49 
   - [x] rref docstrings #43
 - [x] Move `references.md` under `docs` and use `@refs` in docstrings #40 
 - [x] Fix aesthetic issues in documentation (e.g. the `!!! note` in the homepage is not rendered correctly #50
 - [x] Since the package isn't released yet, comment out `docs stable` badge #40
 - [x] Restructure API page in documentation #50
