### ISSUE TITLE
generic solve interface

### ISSUE THREAD

**Issue by lucaferranti** [lucaferranti/IntervalLinearAlgebra.jl#38]
Now that we have different preconditioning mechanisms and solvers, it's time to polish the generic `solve` interface

- [x] Extend [CommonSolve.jl](https://github.com/SciML/CommonSolve.jl) [#42](#42)
- [x] At the moment the solution using Oettli-Präger has its stand alone solver `oettli` I guess that should also be a solver like the others [#41](#41)
- [x] implement generic interface with different methods that decide the preconditioning based on the matrix type and the algorithms, e.g. [#42](#42)
```julia
function _default_precondition(A, method::AbstractSolver)
    # ....
end

# specific default preconditioning methods
function _default_precondition(A, method::GaussElimination)
    if is_sdd_matrix || is_M_matrix 
        return NoPrecondition()
    else
        return InverseMidpoint()
    end
end

function _default_solver()
    GaussEliminiation()
end

function solve(A, b,
               solver::AbstractSolver=_default_solver(),
               precondition::AbstractPrecondition=_default_precondition(A, method))
   
    # precondition
    Ap, bp = precondition(A, b)

    # compute solution
    return solver(Ap, bp)
end
```

**Comment by lucaferranti** [comment]
fixed in the above linked PRs
